name: CI

on: pull_request

jobs:
  phpcs:
    name: WPCS
    runs-on: ubuntu-latest

    container:
      image: php:8.0

    steps:
      - uses: actions/checkout@v4

      - name: Setup Tools
        run: |
          apt-get update && apt-get install -y unzip
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: Install PHP_CodeSniffer
        run: composer install --working-dir=./siteimprove-accessibility --prefer-dist --no-progress --no-suggest

      - name: Check PHP Code Sniff
        run: ./siteimprove-accessibility/vendor/bin/phpcs siteimprove-accessibility --standard=phpcs.xml.dist --report-summary

  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y openssh-client
          mkdir -p ~/.ssh
          echo "${{ secrets.CI_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          echo "@siteimprove:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.CI_TOKEN }}" >> ~/.npmrc
          npm install

      - name: Run ESLint
        run: npx eslint siteimprove-accessibility