name: WPCS check

on: push

jobs:
  phpcs:
    name: WPCS
    runs-on: ubuntu-latest

    container:
      image: php:8.0

    steps:
      - uses: actions/checkout@v2

      - name: Setup Tools
        run: |
          apt-get update && apt-get install -y unzip
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: Install PHP_CodeSniffer
        working-directory: ./plugin-src
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Configure PHPCS
        working-directory: ./plugin-src
        run: ./vendor/bin/phpcs --config-set installed_paths ./vendor/phpcsstandards/phpcsextra,./vendor/phpcsstandards/phpcsutils,./vendor/wp-coding-standards/wpcs

      - name: Check PHP Code Sniff
        working-directory: ./plugin-src
        run: ./vendor/bin/phpcs . --standard=../phpcs.xml.dist --report-summary
